title: Devika Gumaste
logo: /assets/img/logo.png
description: MS Electrical Engineering (Deep Learning) student at Columbia University
show_downloads: true
google_analytics: UA-153190190-1
theme: jekyll-theme-minimal
resume_path: /assets/docs/resume.pdf