# Site settings
name: Devika Gumaste
title: Devika Gumaste | Machine Learning Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://devika3370.github.io/
baseurl: ''
email: dg3370@columbia.edu
cover: https://devika3370.github.io/img/og.png
logo: https://devika3370.github.io/img/emojis/technologist.png
resume: https://devika3370.github.io/resume.pdf
social:
  - title: email
    url: mailto:dg3370@columbia.edu
  - title: github
    url: https://github.com/devika3370
  - title: linkedin
    url: https://www.linkedin.com/in/devika-gumaste

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
