title: Devika Gumaste
logo: /assets/img/logo.png
description: Master's student at Columbia University, specializing in Deep Learning
show_downloads: true
google_analytics: UA-153190190-1
theme: jekyll-theme-minimal
resume_path: /assets/docs/resume.pdf